### ISSUE TITLE
Utils.py file..

### ISSUE THREAD

**Issue by VinuAbraham** [valeriano-manassero/tfx-kubeflow-pipelines#20]
Hey I would like to use your inat example. Is there any detailed documentation for the util.py file..

**Comment by valeriano-manassero** [comment]
As you can see from README, at the moment, inat example needs to be updated. If you have specific questions I can try to help you having this example going while I'm working on it.

**Comment by VinuAbraham** [comment]
Following error occured when i was running inat example...



ValueError: An error occured while trying to apply the transformation: "Input to reshape is a tensor with 561000 values, but the requested shape has 49152
	 [[{{node Reshape}}]]".

**Comment by valeriano-manassero** [comment]
Thank you for you feedback.

I will try to figure out this as soon as possible. In the meanwhile, any proposed PR is more than welcome.

**Comment by VinuAbraham** [comment]
The error happened while I was trying to implement the example on a custom cat and dog dataset.. I think the probelm is with the reshape code in preprocessing func....Dimensions of my image are different for each image....

**Comment by VinuAbraham** [comment]
Is there any way to resize the image....

**Comment by VinuAbraham** [comment]
> The error happened while I was trying to implement the example on a custom cat and dog dataset.. I think the probelm is with the reshape code in preprocessing func....Dimensions of my image are different for each image....

is there any way to resize the images to a common dimension??

**Comment by valeriano-manassero** [comment]
> > The error happened while I was trying to implement the example on a custom cat and dog dataset.. I think the probelm is with the reshape code in preprocessing func....Dimensions of my image are different for each image....
> 
> is there any way to resize the images to a common dimension??

In this case, you need to prepare dataset in a different way before starting a pipeline on it.

**Comment by valeriano-manassero** [comment]
> > The error happened while I was trying to implement the example on a custom cat and dog dataset.. I think the probelm is with the reshape code in preprocessing func....Dimensions of my image are different for each image....
> 
> is there any way to resize the images to a common dimension??

In this case, you need to prepare dataset in a different way before starting a pipeline on it.

Check the fifth cell in file https://github.com/valeriano-manassero/tfx-kubeflow-pipelines/blob/master/inat-2019/data-preparation.ipynb

As you can see the procedure is going to resize all the images, maybe yu can adapt this procedure to get the right dataset and then start the iNat pipeline.

**Comment by VinuAbraham** [comment]
Got it working till transform..But when I am using trainer component this error pops up:
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'

I think the iterator is depreciated ..Any alternatives??

**Comment by VinuAbraham** [comment]
Thanks for the examples..I have completed the pipeline and successfully integrated it with airflow...
Thanks again for the help...

**Comment by amans191** [comment]
Hi, could you please provide how fixed this error:
AttributeError: 'PrefetchDataset' object has no attribute 'make_one_shot_iterator'

Thank you
