### ISSUE TITLE
Provide a preview for tfx-kubeflow-pipelines/cifar-10/data-preparation.ipynb in github webpage

### ISSUE THREAD

**Issue by robertlugg** [valeriano-manassero/tfx-kubeflow-pipelines#8]
I would like to get a preview of data-preparation.ipynb within the github page.  I don't know why yours doesn't appear.  If you can do anything to make it appear, it would be helpful.

**Comment by valeriano-manassero** [comment]
`data-preparation.ipynb` have no output atm since it simply downloads, unpacks and creates tfrecord files for cifar-10 example. Maybe are you referring to `interactive.ipynb` cells output?

If yes, I'm going to update these notebooks with output very soon.

**Comment by valeriano-manassero** [comment]
@robertlugg new notebooks I merged are good enough?
